name: deploy-container

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Add AWS CLI to PATH
        run: echo "/opt/hostedtoolcache/aws/0.0.0/x64/bin" >> $GITHUB_PATH
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          
